image: composer

build:
  stage: build
  script:
    composer install
  artifacts:
    paths:
      - vendor
    untracked: true

environment:
  stage: build
  script:
    - mv "$ENVIRONMENT" "$(pwd)/.env"
  artifacts:
    paths:
      - .env
    untracked: true

test:
  stage: test
  dependencies: 
    - build
    - environment
  script:
    vendor/bin/phpunit