image: prooph/composer:7.2

build:
  stage: build
  script:
    composer install
  artifacts:
    paths:
      - vendor
    untracked: true

test:
  stage: test
  dependencies: 
    - build
  script:
    vendor/bin/phpunit