image: composer

build:
  stage: build
  script:
    composer install
  artifacts:
    paths:
      - vendor
    untracked: true

environment:
  stage: build
  script:
    - cp "$ENVIRONMENT" "$(pwd)/.env"
    - cat .env
    - cat "$(pwd)/.env"

test:
  stage: test
  dependencies: 
    - build
  script:
    vendor/bin/phpunit